### ISSUE TITLE
[Epic] Road to v1.0.0

### ISSUE THREAD

**Issue by jacojoubert** [emberui/emberui#105]
Issues that need to be resolved before we exit beta:

### Option List
- [ ] Figure out how to handle a ton of options

### Month
- [ ] Fix browser zoom breaking visual render

### Addon
- [ ] Improve addon generators
- [ ] Clean up separation between theme and base css

### Website
- [ ] Fix bookmarks so they scroll down and don't attempt route transition
- [ ] Improve Docs
